Linearna regresija

##Dohvacanje podataka

In [ ]:
from sklearn import datasets
baza=datasets.fetch_openml('bodyfat')

In [ ]:
baza.keys()

In [ ]:
import numpy as np
podaci=np.array(baza.data)
podaci

In [ ]:
baza.feature_names

In [59]:
tezina=podaci[:,2]   #zavisna varijabla
tezina=tezina*0.46

In [60]:
visina=podaci[:,3]*2.54  #nezavisna


In [61]:
X=visina
y=tezina

###Grafički prikaz podataka

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(X,y)
plt.xlabel('Visinu u cm')
plt.ylabel('Tezina u kg')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(X,y)
plt.xlabel('Visinu u cm')
plt.ylabel('Tezina u kg')
plt.xlim(150,205)
plt.ylim(40,130)
plt.show()

##Model linearne regresije

In [64]:
X.shape


(252,)

In [65]:
X=X.reshape(-1,1)

In [66]:
X.shape

(252, 1)

In [67]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression().fit(X,y)

In [ ]:
reg.coef_  #nagib pravca

In [ ]:
reg.intercept_  #gdje sjeće os x

In [70]:
y_predvideno=reg.predict(X)

###Koeficijent determinacije
* Relativna mjera prilagođenosti regresijskog pravca
empirijskim podacima
* Dobiva se kao omjer zbroja kvadrata odstupanja tumačenog modelom regresije i ukupnog zbroja kvadrata odstupanja (razlika između izmjerene i prosječne
vrijednosti)
* Model je reprezentativniji što je koeficijent determinacije bliži jedinici (0 – nema veze, 1 - potpuna veza)

In [ ]:
reg.score(X,y)

###Rezidualna odstupanja
* Odstupanja izmjerenih vrijednosti zavisne varijable od regresijskih vrijednosti.
* Model regresije je reprezentativniji što su manja rezidualna odstupanja

In [72]:
visina_21=X[20,0]
stvarna_tezina_21=y[20]
dobivena_tezina_21=round(y_predvideno[20],2)

In [ ]:
print("21. osoba u bazi je visoka {} cm, njena stvarna tezina je {}, a tezina dobivena  regresijskim modelom je {} ".format(visina_21,stvarna_tezina_21,dobivena_tezina_21))

In [ ]:
residualno_odstupanje_21= round(abs(stvarna_tezina_21-dobivena_tezina_21),2)
residualno_odstupanje_21

###Varijanca (eng. Mean squared error)

The smaller the mean squared error, the closer you are to finding the line of best fit

In [76]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y,y_predvideno)

164.7383281629607

###Predviđanje za nepoznatu vrijednost

In [77]:
reg.predict([[180]])

array([83.12141156])

###Grafički prikaz rezultata

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(X,y)
plt.plot(X,y_predvideno,'r')
plt.xlabel('Visinu u cm')
plt.ylabel('Tezina u kg')
#plt.xlim(150,205)
#plt.ylim(40,130)
plt.show()

###Optimizacija

####Izbacivanje outliera 

In [81]:
outlier_X=np.where(X<150)
outlier_X

(array([41]), array([0]))

In [82]:
outlier_y=np.where(y>120)
outlier_y

(array([38, 40]),)

In [83]:
outlier_index=[38,40,41]

In [84]:
X_novi=np.delete(X,outlier_index)
y_novi=np.delete(y,outlier_index)

In [85]:
X_novi.shape

(249,)

In [86]:
X_novi=X_novi.reshape(-1,1)

In [88]:
X_novi.shape

(249, 1)

In [89]:
reg_novi=LinearRegression().fit(X_novi,y_novi)


In [90]:
reg_novi.score(X_novi,y_novi)

0.2823760636283553

In [92]:
y_predvideno_novi=reg_novi.predict(X_novi)

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(X_novi,y_novi)
plt.plot(X,y_predvideno,'r')
plt.plot(X_novi,y_predvideno_novi, 'g')
plt.xlabel('Visinu u cm')
plt.ylabel('Tezina u kg')
plt.xlim(150,205)
plt.ylim(40,130)
plt.show()

In [ ]:
mean_squared_error(y_novi,y_predvideno_novi)

#Multivarijatna linearna regresija

In [ ]:
baza=datasets.fetch_openml('cars')

In [ ]:
baza.keys()

In [ ]:
baza.data.shape

In [ ]:
baza.feature_names

In [101]:
podaci=np.array(baza.data)

In [102]:
X=podaci[50:100,3:6]
y=podaci[50:100,0]

In [ ]:
X.shape

In [ ]:
np.amax(X,axis=0)   #o za max po stupcu, 1 za max po retku

In [ ]:
np.amin(X,axis=0)

In [ ]:
max(y)

In [ ]:
min(y)

####Normalizacija podataka

In [ ]:
from sklearn.preprocessing import normalize

X_norm=normalize(X)
X_norm

In [ ]:
y

In [ ]:
y_norm=y/max(y)
y_norm

In [112]:
reg_car=LinearRegression().fit(X_norm,y_norm)

In [ ]:
reg_car.score(X_norm,y_norm)

In [ ]:
y_pred=reg_car.predict(X_norm)
mean_squared_error(y_norm,y_pred)

####Predviđanje vrijednosti

In [ ]:
reg_car.predict(normalize([[100,3000,20]]))

#Dodatni materijali - Polinomna regresija

In [45]:
#imamo od prije
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression  

#da nam svima budu jednake točke
#import numpy.random as rnd
np.random.seed(42)  

**Generiranje nelinearnih podataka**

In [46]:
#100 točka
X = 6 * np.random.rand(100, 1) - 3
y = 0.5 * X**2 + X + 2 + np.random.randn(100, 1)

**Prikaz podataka**

In [ ]:
plt.scatter(X, y)
plt.xlabel("X")
plt.ylabel("y")
plt.show()

In [ ]:
X[0]

**Dodavanje značajke za polinomnalnu regresiju**

In [49]:
from sklearn.preprocessing import PolynomialFeatures
poly_znacajka = PolynomialFeatures(degree=2, include_bias=False) 
              #degree nam je stupanj funkcije, ako je 2 nam je kvadratna funkcija
X_poly = poly_znacajka.fit_transform(X) 
                #obzirom da su dva stupnja, dodajemo kvadrat


We see here that the transformer has converted our one-dimensional array into a two-dimensional array by taking the exponent of each value. This new, higher-dimensional data representation can then be plugged into a linear regression.

In [ ]:
X_poly[0]

In [ ]:
#primjenjujeno linearnu regresiju
lin_reg = LinearRegression()
lin_reg.fit(X_poly, y)
lin_reg.intercept_, lin_reg.coef_

In [ ]:
y_new = lin_reg.predict(X_poly)
plt.scatter(X, y)
plt.scatter(X, y_new)
plt.xlabel("X")
plt.ylabel("y")
plt.show()

In [ ]:
#da dobijemo lijepu crtu, ravnomjerno raspodjelimo točke i prediktamo

#u intervalu od -3 do 3, ravnomjerno 100 točaka
X_new=np.linspace(-3, 3, 100).reshape(100, 1) 
X_new_poly = poly_znacajka.transform(X_new) #kao i prije dodajemo značajku 
y_new = lin_reg.predict(X_new_poly)  # predvidimo vrijednosti 

plt.plot(X_new, y_new, "r-", linewidth=2, label="Predictions")
plt.scatter(X, y)
plt.xlabel("X")
plt.ylabel("y")
plt.legend(loc="upper left", fontsize=14)
plt.show()

**Pipeline**

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

for style, degree in (("g-", 300), ("b--", 2), ("r-+",1)): 
   #kako hocemo crtati, boja i oznaka i onda stupanj polinoma
    polybig_features = PolynomialFeatures(degree=degree, include_bias=False)
    
    std_scaler = StandardScaler()  
        #Standardize features by removing the mean and scaling to unit variance 
        #Treba nam za ove visokog stupnja, za pravac i kvadratnu ne treba
        #https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
    
    lin_reg = LinearRegression()

    #Sequentially apply a list of transforms and a final estimator. 
    #Intermediate steps of the pipeline must be ‘transforms’,
    # that is, they must implement fit and transform methods. 
    #The final estimator only needs to implement fit.
    
    polynomial_regression = Pipeline([
            ("poly_features", polybig_features),
            ("std_scaler", std_scaler),
            ("lin_reg", lin_reg),
        ])
    polynomial_regression.fit(X, y)
    y_newbig = polynomial_regression.predict(X_new)
    plt.plot(X_new, y_newbig, style, label=str(degree))

plt.scatter(X, y)
plt.legend(loc="upper left")
plt.xlabel("y")
plt.ylabel("y")
plt.axis([-3, 3, 0, 10])

plt.show()